name: Scheduled Job

on:
  schedule:
    - cron: "*/1 * * * *" # Runs every day at midnight

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run a script
        run: echo "Running a scheduled task"
