name: BookStore Scan and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  docker-registry-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run Snyk Vulnerability Scan for Client Dependencies
        uses: snyk/actions/node@master
        with:
          context: ./client
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk Vulnerability Scan for Server Dependencies
        uses: snyk/actions/node@master
        with:
          context: ./api
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Build Client Docker Image
      - name: Build Client Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./client
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_USERNAME }}/bookstore-client:latest
          push: false # Don't push yet, we need to scan first

      # Build Server Docker Image
      - name: Build Server Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./api
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_USERNAME }}/bookstore-server:latest
          push: false # Don't push yet, we need to scan first

      # Scan Client Docker Image for Vulnerabilities using Anchore
      - name: Scan Client Docker Image for Vulnerabilities
        uses: anchore/scan-action@v3
        with:
          image: ${{ secrets.DOCKER_USERNAME }}/bookstore-client:latest
          fail-build: false # Fail the build if critical vulnerabilities are found
          output-format: sarif # Output format for GitHub security report

      # Scan Server Docker Image for Vulnerabilities using Anchore
      - name: Scan Server Docker Image for Vulnerabilities
        uses: anchore/scan-action@v3
        with:
          image: ${{ secrets.DOCKER_USERNAME }}/bookstore-server:latest
          fail-build: false # Fail the build if critical vulnerabilities are found
          output-format: sarif # Output format for GitHub security report

      # Push Client Docker Image to Docker Hub
      - name: Push Client Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./client
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_USERNAME }}/bookstore-client:latest
          push: true

      # Push Server Docker Image to Docker Hub
      - name: Push Server Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./api
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_USERNAME }}/bookstore-server:latest
          push: true
