# Deploy job to build and push Docker images to Docker Hub.
name: BookStore Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  docker-registry-upload:
    # Specify the OS to run the job on.
    runs-on: ubuntu-latest

    # Define the steps to execute in the deployment job.
    steps:
      # Step 1: Checkout the code from the GitHub repository.
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Log in to Docker Hub using Docker Hub credentials stored in GitHub secrets.
      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build and push Docker images for client and server applications.
      - name: Build and Push Client Docker Image
        uses: docker/build-push-action@v6
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: ./client
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/bookstore:client-latest
            ${{ secrets.DOCKER_USERNAME }}/bookstore:client-${{ github.sha }}
          push: true

      - name: Build and Push Server Docker Image
        uses: docker/build-push-action@v6
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: ./api
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/bookstore:api-latest
            ${{ secrets.DOCKER_USERNAME }}/bookstore:api-${{ github.sha }}
          push: true
