name: BookStore Build, Scan, and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  docker-registry-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Docker Metadata for Client Image
      - name: Docker Metadata for Client Image
        id: client_docker_meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/bookstore-client
          flavor: latest=false
          tags: |
            type=ref,event=branch
            type=sha

      # Docker Metadata for Server Image
      - name: Docker Metadata for Server Image
        id: server_docker_meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/bookstore-server
          flavor: latest=false
          tags: |
            type=ref,event=branch
            type=sha

      # Build Client Docker Image
      - name: Build Client Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./client
          tags: ${{ steps.client_docker_meta.outputs.tags }}
          labels: ${{ steps.client_docker_meta.outputs.labels }}
          push: false # Don't push yet, we need to scan first

      # Build Server Docker Image
      - name: Build Server Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./api
          tags: ${{ steps.server_docker_meta.outputs.tags }}
          labels: ${{ steps.server_docker_meta.outputs.labels }}
          push: false # Don't push yet, we need to scan first

      # Scan Client Docker Image for Vulnerabilities using Anchore
      - name: Scan Client Docker Image for Vulnerabilities
        uses: anchore/scan-action@v3
        with:
          image: ${{ secrets.DOCKER_USERNAME }}/bookstore-client:${{ steps.client_docker_meta.outputs.tags }}
          fail-build: true # Fail the build if critical vulnerabilities are found
          output-format: sarif # Output format for GitHub security report

      # Scan Server Docker Image for Vulnerabilities using Anchore
      - name: Scan Server Docker Image for Vulnerabilities
        uses: anchore/scan-action@v3
        with:
          image: ${{ secrets.DOCKER_USERNAME }}/bookstore-server:${{ steps.server_docker_meta.outputs.tags }}
          fail-build: true # Fail the build if critical vulnerabilities are found
          output-format: sarif # Output format for GitHub security report

      # Push Client Docker Image to Docker Hub
      - name: Push Client Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./client
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: ${{ steps.client_docker_meta.outputs.tags }}
          labels: ${{ steps.client_docker_meta.outputs.labels }}
          push: true

      # Push Server Docker Image to Docker Hub
      - name: Push Server Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./api
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: ${{ steps.server_docker_meta.outputs.tags }}
          labels: ${{ steps.server_docker_meta.outputs.labels }}
          push: true
